plugins {
  id "java"
}

group "de.lukasbreuer.spectron"
version "1.0.0-SNAPSHOT"

repositories {
  mavenCentral()
  maven {
    url "https://jitpack.io"
  }
}

dependencies {
  testImplementation "org.junit.jupiter:junit-jupiter-api:6.0.3"
  testImplementation "org.junit.jupiter:junit-jupiter-engine:6.0.3"

  implementation "com.google.inject:guice:7.0.0"

  implementation "com.google.guava:guava:33.6.0-jre"

  implementation "org.projectlombok:lombok:1.18.46"
  annotationProcessor "org.projectlombok:lombok:1.18.46"
  testImplementation "org.projectlombok:lombok:1.18.46"
  testAnnotationProcessor "org.projectlombok:lombok:1.18.46"

  implementation "org.json:json:20251224"

  implementation "io.netty:netty-all:4.2.14.Final"

  implementation "org.seleniumhq.selenium:selenium-java:4.43.0"
  implementation "io.github.bonigarcia:webdrivermanager:6.3.4"

  implementation "dev.dewy:nbt:1.5.1"
}

test {
  useJUnitPlatform()
}

jar {
  duplicatesStrategy(DuplicatesStrategy.EXCLUDE)

  manifest {
    attributes(
      "Main-Class": "de.lukasbreuer.bot.BotApplication",
    )
  }

  from {
    (configurations.runtimeClasspath).collect {
      it.isDirectory() ? it : zipTree(it)
    }
  }

  exclude 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA'
}